### PR TITLE
Adding CI build action (and fix usage of deprecated SPI APIs)

### PR DESCRIPTION
**Pull request by aentinger**
This repository was flagged during semi-automatic review for using any of the SPI APIs `setBitOrder`, `setDataMode`, `setClockDivider`. Unfortunately those SPI APIs are only supported within [ArduinoCore-avr](https://github.com/arduino/ArduinoCore-avr) and deprecated everywhere else.

This is problematic because the `library.properties` of this library indicates that **any** architecture is supported (`architectures=*`) as it raises expectations by the user that simply can not be fulfilled when using this library on any platform that does not support those SPI APIs.

By donating this PR I'm hoping to start a conversation of either limiting the list of supported architectures to avr
```diff
-architectures=*
+architectures=avr
```
or  to adapt the code to use the [SPISettings](https://github.com/arduino/ArduinoCore-avr/blob/master/libraries/SPI/src/SPI.h#L178) API supported in all cores.

### CODE REVIEW

**Comment by noah1510** [comment]
Setting the architecture to only avr is not an option since supporting (almost) every architecture is one of the core features.

I will look into changing to the SPI settings API

**Comment by aentinger** [comment]
Great =) Let me know if you need any help =)

**Comment by noah1510** [comment]
Okay I looked into the code. I already use the SPISettings class for SPI.beginTransaction.
All of the spi code should be in `src/implementations/LedController_low_level.hpp` in the spiTransfer function.
In there `SPISettings` is used for every transaction.

Did you find a call somewhere else that does not use it?

**Comment by noah1510** [comment]
One of the examples uses Adafruit sensors which causes all processors to fail.
Could you add that?

**Comment by aentinger** [comment]
This should do the trick @noah1510: https://github.com/noah1510/LedController/pull/47/commits/657a1e3d4626b4fdfbd533e0c821f41a51defa83 :bow:

**Comment by noah1510** [comment]
looks good I will merge the changes 👍🏻

**Comment by noah1510** [comment]
Could you disable that warnings are treated like errors.
Some of the warnings are expected and there are checks in place to prevent them from causing a problem.

**Comment by aentinger** [comment]
There. You should be all set now.

**Comment by noah1510** [comment]
Your CI files look good. The failing boards are require some code change. I will write a fix for them, so that the CI can pass and your MR merged.

**Comment by aentinger** [comment]
Super ;)

**Comment by noah1510** [comment]
cou you rebase your fork onto the main branch. 54aca23 should get your CI working.

**Comment by aentinger** [comment]
> cou you rebase your fork onto the main branch. [54aca23](https://github.com/noah1510/LedController/commit/54aca237953db6a53210ff6a636a95945f9ec06f) should get your CI working.

Done.

**Comment by noah1510** [comment]
I just removed the function calls that are not part of `api/HardwareSPI.h` so you have to rebase again.

**Comment by aentinger** [comment]
Done :bow:

**Comment by noah1510** [comment]
could you change the ci file so that only the english examples are compiled? The code is identical only the comments differ, so compiling both only causes more CI time/resources than neccassary.

**Comment by noah1510** [comment]
adding `sketch-paths: "examples/english" to the `Compile examples` step should do it.

**Comment by aentinger** [comment]
You can do that yourself ;) As a maintainer you can push on my branch ...

```bash
git remote add alex https://github.com/aentinger-arduino/LedController
git fetch alex
git checkout alex/ci
```

**Comment by noah1510** [comment]
> As a maintainer you can push on my branch ...

I just tried that. It seems I don't have permission to push to that branch.
Its been a while since I created a pull request on github, but at least on gitlab the person creating has to enable a checkmark to allow maintainers to push to their branch. If it is required did you do that?

**Comment by aentinger** [comment]
It should work but I sent you an invite to collaborate on the repo anyway.

**Comment by noah1510** [comment]
> It should work but I sent you an invite to collaborate on the repo anyway.

You have to enable edits by maintainers when opening the pull request I just checked the [github documentation on pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

Either way now that you added me it works. I will squash the commits and then merge the pull request.

**Pull request merged**
